blank_issues_enabled: false
contact_links:
  - name: 🍺 Buy me a beer
    url: https://github.com/chrisfore/anycubic_ha_local#-buy-me-a-beer
    about: If this integration saved you some hassle, you can shout me a beer. Totally optional.
